# Generated by Django 2.2.11 on 2020-08-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='average_speed',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='elapsed_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='elev_high',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='elev_low',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='max_speed',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='run',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='total_elevation_gain',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
